# Generated by Django 2.0.2 on 2018-03-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('0', 'Composite'), ('1', 'Decorator'), ('2', 'Condition'), ('3', 'Action')], max_length=1)),
            ],
        ),
    ]
