# Generated by Django 2.0.2 on 2018-03-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='name',
        ),
    ]
