# Generated by Django 2.0.2 on 2018-03-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_account_tree'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custom_Node',
            new_name='CustomNode',
        ),
    ]
