# Generated by Django 2.0.2 on 2018-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_tree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
